### ISSUE TITLE
Remove the node in the gird

### ISSUE THREAD

**Issue by zhangte113** [cryotools/cosipy#37]
Hello, I come from China and I‘m now a graduate student. It's my pleasure to communicate with you at here.

In your model, the Grid Class has the way of remove_node, which will directly remove a node when this node's height is less than minimum_snow_layer_height. Is there some effect, if I add the node's height, which was removed, to the below layer?
I hope for your reply and please forgive me if there are some errors of grammar and words spell.

Thank you very much!

**Comment by AnsArn** [comment]
Hey just copied Tobias answer:

"Hello and welcome! Are you already a member in slack? If you have any issues in running the model or need help to run the model please use this platform. The remove_node removes the node which is given in the argument of the function, e.g. remove_node(0) removes the first node, remove_node(1) will remove the second node from the top. I am not sure, if I really understand your next question. Do you want to merge two nodes together?
All the best
Tobias"

**Comment by zhangte113** [comment]
Thank you for your answer. I‘m not a number in slack. I had tried to log in slack through my google account, but it informed me that  I have no account in this workspace. Can I be a number in slack? I need to run your modeI for my graduate thesis, and now I only can run a glacier for once a time. I can't run my glacier with restart data for next time. I really want to join you.  
Thank you very much!

**Comment by zhangte113** [comment]
Dear Professor, I had sent you an e-mail by zhangte113@mail.hnust.edu.cn
