### ISSUE TITLE
TypeError when runing COSIPY on the example files

### ISSUE THREAD

**Issue by arbindrakhadka** [cryotools/cosipy#41]
When running cosipy on a newly built Anaconda on the Zhadang example, we get the error message below. Note that we did manage to install and run cosipy on previous Windows installs of Anaconda. Could this be a problem with the version of xarray or pandas?

> Traceback (most recent call last):
> 
>   File "D:\cosipy-master\cosipy\COSIPY.py", line 366, in <module>
>     main()
> 
>   File "D:\cosipy-master\cosipy\COSIPY.py", line 62, in main
>     RESULT = IO.create_result_file()
> 
>   File "D:\cosipy-master\cosipy\cosipy\cpkernel\io.py", line 96, in create_result_file
>     self.init_result_dataset()
> 
>   File "D:\cosipy-master\cosipy\cosipy\cpkernel\io.py", line 305, in init_result_dataset
>     self.add_variable_along_latlon(self.RESULT, self.DATA.HGT, 'HGT', 'm', 'Elevation')
> 
>   File "D:\cosipy-master\cosipy\cosipy\cpkernel\io.py", line 781, in add_variable_along_latlon
>     ds[name] = ((northing,easting), var)
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\dataset.py", line 1563, in __setitem__
>     self.update({key: value})
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\dataset.py", line 4208, in update
>     merge_result = dataset_update_method(self, other)
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\merge.py", line 984, in dataset_update_method
>     return merge_core(
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\merge.py", line 632, in merge_core
>     collected = collect_variables_and_indexes(aligned)
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\merge.py", line 294, in collect_variables_and_indexes
>     variable = as_variable(variable, name=name)
> 
>   File "C:\Users\khadkaa\anaconda3\envs\cosipy\lib\site-packages\xarray\core\variable.py", line 121, in as_variable
>     raise TypeError(
> 
> TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.

**Comment by AnsArn** [comment]
Yes, I think it is an issue with the newest xarray version 0.19.0.

Could you install version 0.18.2 and test if it works?

**Comment by FannyBrun** [comment]
Sorry for not following on the thread. Yes we rolled back to the xarray version 0.18.2 and it worked fine. Thanks!

**Comment by xiaoheijie** [comment]
Can COSIPY run normally on Windows system now?

**Comment by AnsArn** [comment]
The main run can be exected on Windows systems. Only the preprocessing step to create the static file is not possible on Windows systems.
