### ISSUE TITLE
About how to join this slack forum?

### ISSUE THREAD

**Issue by xiaoenli4816** [cryotools/cosipy#56]
Hello author,
    I want to join this online forum,

**Comment by Richteny** [comment]
Dear xioenli4816, 

on the README page (main page) you can find the following link: https://cosipy.slack.com/, if that does not work you can forward me your email address or use this link (valid for the next 30 days) to join: https://join.slack.com/t/cosipy/shared_invite/zt-2a7w7zsyf-nqGFGoGlMRVUZxp1qZGX4A .

Best,
Niklas

**Comment by xiaoenli4816** [comment]
Dear  Niklas，
      I had joined this cosipy slack, thank you very much.
Best,
  xiaoen

Niklas Richter ***@***.***> 于2024年1月11日周四 20:57写道：

**Comment by Richteny** [comment]
Great, 
welcome on board! I will close this issue then

**Comment by xiaoenli4816** [comment]
Thanks for your support.

Niklas Richter ***@***.***> 于2024年1月11日周四 21:05写道：
