### ISSUE TITLE
GRB source injector in tutorials

### ISSUE THREAD

**Issue by tiffanylewisphd** [cryotools/cosipy#70]
The GRB source injector may be historical, but it is currently in the tutorials and uses cosipy.coordinates.orientation, which is "not found" the way that the current version runs. It should either be fixed or removed before a public release to avoid confusion.

**Comment by gampnico** [comment]
Please may you be more specific (eg a file name)? Whereabouts is this in the tutorial?

**Comment by tiffanylewisphd** [comment]
The file is GRB_source_injector.ipynb in tutorials/source_injector.

**Comment by gampnico** [comment]
I believe you are looking for [COSITools](https://github.com/cositools/cosipy/). This repo is for a surface energy and mass balance model for glaciers, also called COSIPY.
